### ISSUE TITLE
Update to JSAPI 3.13

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-slurp-example#16]
Update esri slurp to [1.41](https://github.com/steveoh/grunt-esri-slurp/releases/tag/v1.4.1), JSAPI to 3.13, and Dojo as follows:

Version 3.13 of the ArcGIS API for JavaScript uses Dojo 1.10.4. dgrid version 0.3.17. put-selector version 0.3.6 and xstyle version 0.1.3 are also included.

**Comment by tsamaya** [comment]
it seems to work with esri slurp 1.4.2 on this repo (my fork and commit : https://github.com/tsamaya/esri-slurp-example/commit/39f9eb57a422d37c38cd7c7bec84d32256cdee14). but not on dojo-bootstrap-map-js. Still investigating !
