### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tsamaya** [tomwayson/esri-slurp-example#19]
The section "Comparing the Built App" links to  "Create a map sample page".

Point to "Search multiple sources" https://developers.arcgis.com/javascript/jssamples/search_multiplesources.html

And then create a new spreadsheet to compare scripts and requests

**Comment by tomwayson** [comment]
Already working on this. Initial pass at the stats was interesting....

**Comment by tomwayson** [comment]
So, on my PC (src and dist folders hosted under IIS) I get the following:

Page | JS Requests | JS KB (gzipped) | JS KB (uncompressed)
------ | ----------------- | ------------- | --------------- | ---------------
dist/index.html | 1 | 304 | 792
samples/search_multiplesources_compact.html | 23 | 276 | 850
samples/search_multiplesources.html | 7 | 337 | 1091
samples/search_multiplesources_compact.html | 23 | 348 | 850

It looks like my IIS gzip compression is probably not as good as that used by whatever is serving the hosted JSAPI from the CDN. So I downloaded the JSAPI and served it locally off my PC (via IIS) and got the following results by pointing the sample pages at the locally hosted JSAPI builds (regular and compact)

Page | JS Requests | JS KB (gzipped) | JS KB (uncompressed)
------ | ----------------- | ------------- | --------------- | ---------------
dist/index.html | 1 | 304 | 792
samples/search_multiplesources_compact.html | 23 | 348 | 850
samples/search_multiplesources.html | 7 | 431 | 1091

The moral of this story is, **your mileage may vary and there are many factors to consider when deciding whether or not it is worth while to do a Dojo build.**

I'm going to update README to that effect when I get a chance.
