### ISSUE TITLE
Can´t build dojo on Debian Wheezy

### ISSUE THREAD

**Issue by majales** [tomwayson/esri-slurp-example#20]
Hi, I was trying esri-slurp-example for the first time yesterday and I'm unable to build dojo.
It always says ">> Error Warning: Task "dojo:dist" failed" I have tried several times but is always the same. Is there any ways to debug what is failing? Should I just "git clone https://github.com/tomwayson/esri-slurp-example" and then follow your instructions? Or is there something else I shoul do or check?

**Comment by tsamaya** [comment]
Hi,
can you tell me which plateform are you using ? (OS, version, node version,
grunt version)

you followed these instructions without warning nor error :

npm install

bower install

grunt slurp



the dojo build occurs when using that command:

grunt build



You can use

grunt build *--verbose*


You will have additional informations and share them with us.


Arnaud

**Comment by majales** [comment]
Hi, I'm using Debian Wheezy with wheezy-backports repository activated.

node v0.10.29
npm 2.7.3
bower 1.3.12
grunt-cli v0.1.13
grunt v0.4.5

grunt  build --verbose
Initializing
Command-line options: --verbose

Reading "gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-esri-slurp" local Npm module tasks.
Reading /home/admin/esri-slurp-example/node_modules/grunt-esri-slurp/package.json...OK
Parsing /home/admin/esri-slurp-example/node_modules/grunt-esri-slurp/package.json...OK
Loading "index.js" tasks...OK
+ esri_slurp, esri_slurp_modules

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /home/admin/esri-slurp-example/node_modules/grunt-contrib-clean/package.json...OK
Parsing /home/admin/esri-slurp-example/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-connect" local Npm module tasks.
Reading /home/admin/esri-slurp-example/node_modules/grunt-contrib-connect/package.json...OK
Parsing /home/admin/esri-slurp-example/node_modules/grunt-contrib-connect/package.json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-dojo" local Npm module tasks.
Reading /home/admin/esri-slurp-example/node_modules/grunt-dojo/package.json...OK
Parsing /home/admin/esri-slurp-example/node_modules/grunt-dojo/package.json...OK
Loading "dojo.js" tasks...OK
+ dojo

Registering "grunt-string-replace" local Npm module tasks.
Reading /home/admin/esri-slurp-example/node_modules/grunt-string-replace/package.json...OK
Parsing /home/admin/esri-slurp-example/node_modules/grunt-string-replace/package.json...OK
Loading "string-replace.js" tasks...OK
+ string-replace
Loading "gruntfile.js" tasks...OK
+ build, slurp

Running tasks: build

Running "build" task

Running "clean:dist" (clean) task
Verifying property clean.dist exists in config...OK
Files: [no src] -> dist
Options: force=false, no-write=false
>> 0 paths cleaned.

Running "dojo" task

Running "dojo:dist" (dojo) task
Verifying property dojo.dist exists in config...OK
File: [no files]
Options: dojo="src/dojo/dojo.js", load="build", profile="profiles/app.profile.js", profiles=null, appConfigFile=null, package=null, packages=null, require=null, requires=null, releaseDir="../dist", cwd="./", dojoConfig=null, basePath="./src"

Building Dojo...
Dojo build parameters:
        src/dojo/dojo.js
        load=build
        --basePath ./src
        --profile profiles/app.profile.js
        --profile profiles/app.profile.js
        --releaseDir ../dist
processing profile resource /home/admin/esri-slurp-example/profiles/app.profile.js
processing profile resource /home/admin/esri-slurp-example/profiles/app.profile.js
warn(209) Missing or empty package.json. filename: /home/admin/esri-slurp-example/src/app/package.json
info(107) Package Version: package: dgrid; version: 0.3.17
processing profile resource /home/admin/esri-slurp-example/src/dgrid/package.js
info(107) Package Version: package: dijit; version: 1.10.4
processing profile resource /home/admin/esri-slurp-example/src/dijit/dijit.profile.js
info(107) Package Version: package: dojo; version: 1.10.4
processing profile resource /home/admin/esri-slurp-example/src/dojo/dojo.profile.js
info(107) Package Version: package: dojox; version: 1.10.4
processing profile resource /home/admin/esri-slurp-example/src/dojox/dojox.profile.js
info(107) Package Version: package: esri; version: 3.13
processing profile resource /home/admin/esri-slurp-example/src/esri/esri.profile.js
info(107) Package Version: package: put-selector; version: 0.3.6
processing profile resource /home/admin/esri-slurp-example/src/put-selector/package.js
info(107) Package Version: package: xstyle; version: 0.1.2
processing profile resource /home/admin/esri-slurp-example/src/xstyle/package.js
discovering resources...
starting reading resources...
starting processing raw resource content...
starting tokenizing resource...
starting processing resource tokens...
starting parsing resource...
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
>> Error
Warning: Task "dojo:dist" failed. Use --force to continue.

Aborted due to warnings.

Seems bower has some problems...

**Comment by majales** [comment]
Forgot to report bower

bower list
bower check-new     Checking for new versions of the project dependencies..
esri-slurp-example#0.1.2 /home/admin/esri-slurp-example
├── dgrid#0.3.17 (latest is 0.4.0)
├── dijit#1.10.4
├── dojo#1.10.4
├── dojox#1.10.4
├── put-selector#0.3.6
├── util#1.10.4
└── xstyle#0.1.3 (latest is 0.3.1)

**Comment by tsamaya** [comment]
I see Error: spawn ENOENT

as I am at work I can not digg for it right now. I will come back to you as
soon as possible.

2015-03-24 10:55 GMT+01:00 majales <notifications@github.com>:

**Comment by majales** [comment]
Thanx for support. I'll try it on centos 6.6 later afternoon today.

**Comment by tomwayson** [comment]
Does your system have Java installed? [The Dojo build requires Java](http://stackoverflow.com/questions/20810736/why-dojo-build-does-not-wok).

**Comment by tsamaya** [comment]
Good hint. As a java addict, I can't figure out not having java. just check
a xubuntu virtual machine, no java... this is not mine

2015-03-24 16:08 GMT+01:00 Tom Wayson <notifications@github.com>:

**Comment by majales** [comment]
Hi,
It was java missing. After installing jre-headless it compiled without errors just with 81 warnings. Thanx for help.
