### ISSUE TITLE
Graphics rendering issues IE8

### ISSUE THREAD

**Issue by gavlepeter** [tomwayson/esri-slurp-example#22]
Hello!

I have been using this great example to successfully create a build but I noticed graphics on IE8 wont render. ESRI JS API use dojox/gfx/vml for rendering graphics on IE 6-8. I have tried including this in my build profile but still no graphics. It's the same problem with the unbuilt source.

I read the official ESRI build report and it looks like a few custom dojox layers is included (listed below). I also tried adding these layers to my build profile without success.

If I grab the built dojox/gfx source from the ESRI official build and replace my unbuilt dojox/gfx source the graphics works fine. I'm guessing the dojox/gfx source have been modified in some way by esri in their official build?

Any help or ideas would be appreciated!

dojox/gfx/vml:
	dojox/gfx/arc
	dojox/gfx/shape
	dojox/gfx/vml
	dojox/gfx/gradient
	dojox/gfx/path

dojox/gfx/svg:
	dojox/gfx/shape
	dojox/gfx/path
	dojox/gfx/svg

dojox/gfx/canvas:
	dojox/gfx/arc
	dojox/gfx/shape
	dojox/gfx/canvas
	dojox/gfx/bezierutils
	dojox/gfx/path
	dojox/gfx/decompose

**Comment by tomwayson** [comment]
Closing as this repo is now deprecated. Use [bower build](https://developers.arcgis.com/javascript/jshelp/inside_bower_custom_builds.html) instead.

Report any issues to the [jsapi-resources repo](https://github.com/Esri/jsapi-resources/issues).
