### ISSUE TITLE
Use grunt execute

### ISSUE THREAD

**Issue by davewilton** [tomwayson/esri-slurp-example#23]
Tom, I've already branched your code and taken it in a different direction. I understand it is not possible to fork a repo twice, but then I don't understand how to create a pull request. I tried creating a branch and making one from there but the git UI just gives an error. If you have any tips on how I can make the pull request please let me know (sorry git is not my day to day source control)

Basically this is my pull request:

Changed the build to run with node rather than java. This resulted in a build which was 134 seconds vs 177 seconds in my test. I have seen much better results though with larger projects. This involved adding grunt-execute. I have also removed all grunt-dojo items.

//use node to execute dojo as it is much quicker. based upon original boilerplate calls
	execute: {
        dojoBuild: {
            // execute javascript files in a node child_process 
            src: ['src/dojo/dojo.js'], // Path to dojo.js file in dojo source']
			cwd: './', // Directory to execute build within
			options: {
				args: [ 'load=build', '--profile', 'profiles\\app.profile-nodojo.js', 'releaseDir=../dist']
				} 
        }
	},

  grunt.loadNpmTasks('grunt-execute');

  grunt.registerTask('build', ['clean:dist', 'execute:dojoBuild', 'string-replace']);

**Comment by tsamaya** [comment]
I think for now the best way is to use git command line or try branching with [SourceTree](https://www.atlassian.com/software/sourcetree/overview). 

Github is working on a new desktop application the beta for windows is out https://desktop.github.com/

**Comment by tomwayson** [comment]
@davewilton 

As you mention in #24, it's actually closure that is launching Java. It appears that [grunt-dojo is running the build in node](https://github.com/phated/grunt-dojo/blob/master/tasks/dojo.js#L189), so no need to use something like grunt-execute.
