### ISSUE TITLE
Support for 3.14

### ISSUE THREAD

**Issue by sbhodge80** [tomwayson/esri-slurp-example#25]
Hi Tom,

ESRI have released version 3.14.  The readme for grunt-esri-slurp by steveoh says version 2.0.1 has been updated with the 3.14 module list.  I'm not sure how to use grunt-esri-slurp directly though and wondered if you would update esri-slurp-example to also support 3.14?

Simon
PS. Thanks for putting this together in the first place!

**Comment by tomwayson** [comment]
resolved in [v0.1.4](https://github.com/tomwayson/esri-slurp-example/releases/tag/v0.1.4)
