### ISSUE TITLE
Use a better sample page

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-slurp-example#8]
The [Create a map sample page](https://developers.arcgis.com/javascript/jssamples/map_simple.html) page isn't the best example of the value of doing a custom build. Probably should at the very least use a sample that includes a feature layer, and probably something that uses modules that are not included in the main JSAPI build (i.e. something from `esri/dijit`?).

**Comment by tsamaya** [comment]
one of these two looks perfect (dijit and FL):
- https://developers.arcgis.com/javascript/jssamples/search_multiplesources.html
- https://developers.arcgis.com/javascript/jssamples/search_customized.html

**Comment by tomwayson** [comment]
Great idea @tsamaya. I like this one:

https://developers.arcgis.com/javascript/jssamples/search_multiplesources.html

I've added you as a collaborator to this repo, so whomever has a chance to get around to this first (you or I) can self-assign this issue to let the other know they are working on it.

Thanks again for all your great contributions!
